# Site settings 配置站点
title: 'Welcome'
description: 'Liyuhao blog'
keywords: ''
url: https://augustlyh1998.github.io

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/index.html'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: 'LIYUHAO'
NickName: '77'
webtitle: 'LIYUHAO'
bio: ''
about: true
aboutyou1: 'CHINA Chengdu 1998'
aboutyou2: 'Email - 1084399812@qq.com'
portraits: '/assets/profile.jpeg' 

# SNS
SNS: true
SNS-icon: 
  mail: '1084399812@qq.com'
  weixin: '12313'
  qq: '1084399812'
  github: 'https://github.com/AugustLYH1998'
  #Codepen: ''
  weibo: 'null'
  instagram: 'null'
  Twitter: 'null'
  #Dribbble: ''
  Facebook: 'null'
  Google: 'null'
  zhihu: 'null'
  juejin: 'null'
  twitch: 'null'

# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'perldoc'

# 友情链接
friends:
  我的github : https://github.com/AugustLYH1998
  kinghtxg's blog : https://kinghtxg.github.io
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC81MTE5OC8yNzY3OQ==' # MTAyMC81MTE5OC8yNzY3OQ==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: '34952a524e6f09ddef5210d3f57d66e8'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
